export interface NewMemoInterface {
  tipo: string,
  patente: string,
  rut: string,
  nombre: string,
  calle: string,
  numero: string,
  aclaratoria: string,
  periodo: string,
  capital: number,
  afecto: number,
  total: number,
  emision: number,
  fechaPagos: string,
  giro: string,
  agtp: string,
  nombre_representante: string,
  rut_representante: string,
}

export interface DataInterface {
  findMemo: {
    afecto: number,
    agtp: string,
    capital: string,
    direccion: string,
    emision: number,
    giro: string,
    id: string,
    local: {
      nombre_local: string,
      patente: string,
      representantes: string,
      rut_local: string,
    },
    pay_times: {
      day: number,
      memo_id: string,
      month: number,
      year: number,
    },
    periodo: string,
    tipo: string,
    total: string,
  }[],
  message: string,
  nextPage: boolean,
  total: number,
  totalPages: number,
}
