export interface NewMemoInterface {
    tipo: string,
    patente: string,
    rut: string,
    nombre: string,
    calle: string,
    numero: string,
    aclaratoria: string,
    periodo: string,
    capital: number,
    afecto: number,
    total: number,
    emision: number,
    fechaPagos: string,
    giro: string,
    agtp: string,
}